name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH & build + pm2 restart
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.38.86.19 'bash -s' <<'ENDSSH'
            cd /home/ubuntu/projectPractice/project-codiit-fe-main
            git pull
            npm install
            npm run build
            pm2 restart frontend
          ENDSSH
